name: Linux CI

# Trigger on pushes to all branches and for all pull requests
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}

    strategy:
      fail-fast: false
      matrix:
        config:
        # GCC-12
        - {
            name: "Linux GCC 12 Debug (C++17)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: Debug,
            cc: "gcc-12", cxx: "g++-12",
            cxx_standard: 17,
            cxx_coneepts: false,
          }
        - {
            name: "Linux GCC 12 Release (C++17)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: RelWithDebInfo,
            cc: "gcc-12", cxx: "g++-12",
            cxx_standard: 17,
            cxx_coneepts: false,
          }
        - {
            name: "Linux GCC 12 Debug (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: Debug,
            cc: "gcc-12", cxx: "g++-12",
            cxx_standard: 20
          }
        - {
            name: "Linux GCC 12 Release (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: RelWithDebInfo,
            cc: "gcc-12", cxx: "g++-12",
            cxx_standard: 20
          }

          # GCC-13
        - {
            name: "Linux GCC 13 Debug (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: Debug,
            cc: "gcc-13", cxx: "g++-13",
            cxx_standard: 17,
            cxx_coneepts: false,
          }
        - {
            name: "Linux GCC 13 Release (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: RelWithDebInfo,
            cc: "gcc-13", cxx: "g++-13",
            cxx_standard: 17,
            cxx_coneepts: false,
          }
        - {
            name: "Linux GCC 13 Debug (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: Debug,
            cc: "gcc-13", cxx: "g++-13",
            cxx_standard: 20
          }
        - {
            name: "Linux GCC 13 Release (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: RelWithDebInfo,
            cc: "gcc-13", cxx: "g++-13",
            cxx_standard: 20
          }

        # GCC-14
        - {
            name: "Linux GCC 14 Debug (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: Debug,
            cc: "gcc-14", cxx: "g++-14",
            cxx_standard: 17,
            cxx_coneepts: false,
          }
        - {
            name: "Linux GCC 14 Release (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: RelWithDebInfo,
            cc: "gcc-14", cxx: "g++-14",
            cxx_standard: 17,
            cxx_coneepts: false,
          }
        - {
            name: "Linux GCC 14 Debug (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: Debug,
            cc: "gcc-14", cxx: "g++-14",
            cxx_standard: 20
          }
        - {
            name: "Linux GCC 14 Release (C++20, Concepts)", artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: RelWithDebInfo,
            cc: "gcc-14", cxx: "g++-14",
            cxx_standard: 20
          }

        # # Clang-10
        # - {
        #     name: "Linux Clang 10 Debug (C++20 / ASAN)", artifact: "Linux.tar.xz",
        #     os: ubuntu-latest,
        #     container: "ubuntu:18.04",
        #     build_type: Debug,
        #     cc: "clang-10", cxx: "clang++-10",
        #     cxx_standard: 20,
        #     cxx_asan: true,
        #     cxx_concepts: false
        #   }
        # - {
        #     name: "Linux Clang 10 Release (C++20 / Concepts)", artifact: "Linux.tar.xz",
        #     os: ubuntu-latest,
        #     container: "ubuntu:18.04",
        #     build_type: RelWithDebInfo,
        #     cc: "clang-10", cxx: "clang++-10",
        #     cxx_standard: 20,
        #   }
        
        # # Clang-10
        # - {
        #     name: "Linux Clang 10 Debug (C++20 / ASAN)", artifact: "Linux.tar.xz",
        #     os: ubuntu-latest,
        #     container: "ubuntu:18.04",
        #     build_type: Debug,
        #     cc: "clang-10", cxx: "clang++-10",
        #     cxx_standard: 20,
        #     cxx_asan: true,
        #     cxx_concepts: false
        #   }
        # - {
        #     name: "Linux Clang 10 Release (C++20 / Concepts)", artifact: "Linux.tar.xz",
        #     os: ubuntu-latest,
        #     container: "ubuntu:18.04",
        #     build_type: RelWithDebInfo,
        #     cc: "clang-10", cxx: "clang++-10",
        #     cxx_standard: 20,
        #   }

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'

    - name: Install GCC or Clang
      shell: bash
      run: |
        sudo apt-get install -y ${{matrix.config.cc}} ${{matrix.config.cxx}}

    - name: Install libc++
      id: install_libcxx
      if: matrix.config.libcxx
      shell: bash
      working-directory: ${{ env.HOME }}
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        $GITHUB_WORKSPACE/install_libcxx.sh

    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${{ matrix.config.cc }})
        set(ENV{CXX} ${{ matrix.config.cxx }})

        set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}:$ENV{PATH}")

        if ("x${{ matrix.config.libcxx }}" STREQUAL "xtrue")
          set(cxx_flags "${cxx_flags} -stdlib=libc++ -nostdinc++ -cxx-isystem $ENV{GITHUB_WORKSPACE}/llvm/include/c++/v1/ -Wno-unused-command-line-argument")
          set(link_flags "${link_flags} -L $ENV{GITHUB_WORKSPACE}/llvm/lib -Wl,-rpath,$ENV{GITHUB_WORKSPACE}/llvm/lib -lc++abi")
        endif()

        if ("${{ matrix.config.cxx }}" MATCHES "clang.*")
            # clang spurious warning on <=> use
            set(cxx_flags "${cxx_flags} -Wno-zero-as-null-pointer-constant")
        endif()

        if ("x${{ matrix.config.cxx_asan }}" STREQUAL "xtrue")
          set(cxx_flags "${cxx_flags} -fsanitize=address")
          set(cxx_flags "${cxx_flags} -fno-omit-frame-pointer")
        endif()

        set(cxx_concepts ON)
        if ("x${{ matrix.config.cxx_concepts }}" STREQUAL "xfalse")
          set(cxx_concepts OFF)
        endif()

        execute_process(
          COMMAND cmake
            -S .
            -B build
            -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
            -D CMAKE_CXX_STANDARD:STRING=${{ matrix.config.cxx_standard }}
            -D "CMAKE_CXX_FLAGS:STRING=${cxx_flags}"
            -D "CMAKE_EXE_LINKER_FLAGS:STRING=${link_flags}"
            -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON
            -D RANGE_V3_HEADER_CHECKS:BOOL=ON
            -D RANGES_PREFER_REAL_CONCEPTS:BOOL=${cxx_concepts}
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status: ${result}")
        endif()

    - name: Build
      shell: cmake -P {0}
      continue-on-error: ${{ matrix.config.experimental || false }}
      run: |
        set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}:$ENV{PATH}")

        include(ProcessorCount)
        ProcessorCount(proc_count)

        execute_process(
          COMMAND cmake --build build --parallel ${proc_count}
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status: ${result}")
        endif()

    - name: Run tests
      shell: cmake -P {0}
      continue-on-error: ${{ matrix.config.experimental || false }}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)

        set(ENV{CTEST_OUTPUT_ON_FAILURE} "ON")

        execute_process(
          COMMAND ctest --verbose --parallel ${N}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()
