name: MacOS CI

# Trigger on pushes to all branches and for all pull-requests
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        # AppleClang
        - {
            name: "macOS Clang Debug (C++17)", artifact: "macOS.tar.xz",
            os: macos-13,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cxx_standard: 17,
            cxx_asan: true,
          }
        - {
            name: "macOS Clang Release (C++17)", artifact: "macOS.tar.xz",
            os: macos-13,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cxx_standard: 17,
          }
        - {
            name: "macOS Clang Debug (C++20 / ASAN)", artifact: "macOS.tar.xz",
            os: macos-13,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cxx_standard: 20,
            cxx_asan: true,
          }
        - {
            name: "macOS Clang Release (C++20)", artifact: "macOS.tar.xz",
            os: macos-13,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cxx_standard: 20,
          }

        - {
            name: "macOS Clang Debug (C++17)", artifact: "macOS.tar.xz",
            os: macos-14,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cxx_standard: 17,
            cxx_asan: true,
          }
        - {
            name: "macOS Clang Release (C++17)", artifact: "macOS.tar.xz",
            os: macos-14,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cxx_standard: 17,
          }
        - {
            name: "macOS Clang Debug (C++20 / ASAN)", artifact: "macOS.tar.xz",
            os: macos-14,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cxx_standard: 20,
            cxx_asan: true,
          }
        - {
            name: "macOS Clang Release (C++20)", artifact: "macOS.tar.xz",
            os: macos-14,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cxx_standard: 20,
          }

        - {
            name: "macOS Clang Debug (C++17)", artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cxx_standard: 17,
            cxx_asan: true,
          }
        - {
            name: "macOS Clang Release (C++17)", artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cxx_standard: 17,
          }
        - {
            name: "macOS Clang Debug (C++20 / ASAN)", artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cxx_standard: 20,
            cxx_asan: true,
          }
        - {
            name: "macOS Clang Release (C++20)", artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cxx_standard: 20,
          }

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'

    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${{ matrix.config.cc }})
        set(ENV{CXX} ${{ matrix.config.cxx }})

        # set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}:$ENV{PATH}")

        if ("x${{ matrix.config.libcxx }}" STREQUAL "xtrue")
          set(cxx_flags "${cxx_flags} -stdlib=libc++ -nostdinc++ -cxx-isystem $ENV{GITHUB_WORKSPACE}/llvm/include/c++/v1/ -Wno-unused-command-line-argument")
          set(link_flags "${link_flags} -L $ENV{GITHUB_WORKSPACE}/llvm/lib -Wl,-rpath,$ENV{GITHUB_WORKSPACE}/llvm/lib -lc++abi")
        endif()

        if ("${{ matrix.config.cxx }}" MATCHES "clang.*")
            # clang spurious warning on <=> use
            set(cxx_flags "${cxx_flags} -Wno-zero-as-null-pointer-constant")
        endif()

        if ("x${{ matrix.config.cxx_asan }}" STREQUAL "xtrue")
          set(cxx_flags "${cxx_flags} -fsanitize=address")
          set(cxx_flags "${cxx_flags} -fno-omit-frame-pointer")
        endif()

        set(cxx_concepts ON)
        if ("x${{ matrix.config.cxx_concepts }}" STREQUAL "xfalse")
          set(cxx_concepts OFF)
        endif()

        execute_process(
          COMMAND cmake
            -S .
            -B build
            -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
            -D CMAKE_CXX_STANDARD:STRING=${{ matrix.config.cxx_standard }}
            -D "CMAKE_CXX_FLAGS:STRING=${cxx_flags}"
            -D "CMAKE_EXE_LINKER_FLAGS:STRING=${link_flags}"
            -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON
            -D RANGE_V3_HEADER_CHECKS:BOOL=ON
            -D RANGES_PREFER_REAL_CONCEPTS:BOOL=${cxx_concepts}
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status: ${result}")
        endif()

    - name: Build
      shell: cmake -P {0}
      continue-on-error: ${{ matrix.config.experimental || false }}
      run: |
        # set(ENV{PATH} "$ENV{GITHUB_WORKSPACE}:$ENV{PATH}")

        include(ProcessorCount)
        ProcessorCount(proc_count)

        execute_process(
          COMMAND cmake --build build --parallel ${proc_count}
          RESULT_VARIABLE result
        )

        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status: ${result}")
        endif()

    - name: Run tests
      shell: cmake -P {0}
      continue-on-error: ${{ matrix.config.experimental || false }}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)

        set(ENV{CTEST_OUTPUT_ON_FAILURE} "ON")

        execute_process(
          COMMAND ctest --verbose -j ${N}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()
